Prevent warning with epoll when variable is set but not used.
.../src/socket.cpp:2890:13: error: variable events set but not used [-Werror=unused-but-set-variable=]
 2890 |         int events = 0;

Reference: https://bugs.gentoo.org/960831
Signed-off-by: Jaco Kroon <jaco@uls.co.za>