Fix missing fileno() on Cygwin.
Fixes this error, caused by the library being strict and removing
support for fileno() when using -std=c++11. Instead, we'll prefer
-std=g++11 if it's available.

    src/socket.cpp:549:21: error: ‘fileno’ was not declared in this
      scope

Closes #193, reported by @Gankarloo.