Fix Solaris build; add missing #include move.
Fixes the following on some platforms:

    /usr/include/netinet/udp.h:26:2: error:
        unknown type name 'in_port_t'

(Missed that one when cherry-picking 483b0eca.)